CREATE DATABASE CITY_HOSPITAL;
USE CITY_HOSPITAL;
CREATE TABLE PATIENTS (
PATIENT_ID INT,
PATIENT_NAME VARCHAR(25),
AGE INT,
GENDER VARCHAR(15),
ADMISSION_DATE DATE
);

ALTER TABLE PATIENTS
ADD DOCTOR_ASSIGNED VARCHAR(50);

ALTER TABLE PATIENTS
MODIFY PATIENT_NAME VARCHAR (100);

ALTER TABLE PATIENTS
RENAME PATIENT_INFO;

TRUNCATE TABLE PATIENT_INFO;
DROP TABLE PATIENT_INFO;
