CREATE DATABASE BOOKSTORE ;
USE BOOKSTORE ;

CREATE TABLE BOOKS (
BookS_Id INT PRIMARY KEY NOT NULL,
Title VARCHAR(100),
Author VARCHAR(50),
Price DECIMAL(10,2)
);

CREATE TABLE ORDERS (
OrderID INT PRIMARY KEY,
BOOKS_ID int ,
OrderDate DATE,
Quantity INT,
FOREIGN KEY (Books_Id) REFERENCES BOOKS(Books_ID) 
) ; 
ALTER TABLE Books
ADD ISBN VARCHAR(20) UNIQUE;
SHOW INDEX FROM Books;
DELETE FROM Orders
WHERE OrderID IN (999, 1000);

TRUNCATE TABLE ORDERS ;
DROP TABLE ORDERS ;
